apps/accounts/urls.py
from django.urls import path
from .views import ProfileView, ExchangeView

app_name = "accounts"

urlpatterns = [
    path("profile/<int:id>/<str:token>/", ProfileView.as_view(), name="profile"),
    path("exchange/", ExchangeView.as_view(), name="exchange"),
]

apps/forums/urls.py
from django.urls import  path
from .views import forum
from .views import answers

app_name = "forums"

forum_urlpatterns = [
    path("", forum.ForumListView.as_view(), name="forum-list"),
    path("create/", forum.ForumCreateView.as_view(), name="create-forum"),
    
    path("<int:id>/<str:slug>/", forum.ForumDetailView.as_view(), name="forum-detail"),

    path("<int:id>/<str:slug>/update/", forum.ForumUpdateView.as_view(), name="update-forum"),
    path("<int:id>/<str:slug>/delete/", forum.ForumDeleteView.as_view(), name="delete-forum"),
]

forum_answers_urlpatterns = [
    path("<int:id>/<str:slug>/answers/", answers.ForumAnswerListView.as_view(), name="forum-answer-list"),
    path("<int:id>/<str:slug>/answers/create/", answers.ForumAnswerCreateView.as_view(), name="create-forum-answer"),
    path(
        "<int:id>/<str:slug>/answers/update/<int:answer_id>/<str:answer_token>/", 
        answers.ForumAnswerUpdateView.as_view(), 
        name="update-forum-answer"
    ),
    path(
        "<int:id>/<str:slug>/answers/delete/<int:answer_id>/<str:answer_token>/", 
        answers.ForumAnswerDeleteView.as_view(), 
        name="delete-forum-answer"
    ),
    path(
        "<int:id>/<str:slug>/answers/accept/<int:answer_id>/<str:answer_token>/", 
        answers.ForumAnswerAcceptView.as_view(), 
        name="accept-forum-answer"
    ),
]

urlpatterns = [
    *forum_urlpatterns,
    *forum_answers_urlpatterns
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.products.views.product import ProductListView

THIRD_PARTY_URLS = [
    path("accounts/", include("allauth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

LOCAL_URLS = [
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("chats/", include("apps.chats.urls")),
    path("orders/", include("apps.orders.urls")),
    
    path("articles/", include("apps.articles.urls")),
    path("forums/", include("apps.forums.urls")),

    path("vote/", include("apps.votes.urls")),
    path("comments/", include("apps.comments.urls")),
]

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('admin/', admin.site.urls),

    *THIRD_PARTY_URLS,
    *LOCAL_URLS,


]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

handler404 = 'apps.orders.views.handler404'
handler500 = 'apps.orders.views.handler500'

apps/forums/models/answer.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from accounts.models import Account
from .forum import Forum
from forums.utils import unique_token_generator
from votes.models import Vote

class ForumAnswer(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='forum_answers')
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE, related_name='answers')
    answer = models.TextField()
    
    date = models.DateTimeField(auto_now=True)
    token = models.CharField(max_length=20, unique=True)

    is_edited = models.BooleanField(default=False)
    is_correct_answer = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.token = unique_token_generator(self.__class__)
            return super().save(*args, **kwargs)

        self.is_edited = True
        return super().save(*args, **kwargs)
    

apps/forums/models/forum.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation

from accounts.models import Account
from votes.models import Vote
from forums.utils import unique_slug_generator


class Forum(models.Model):
    '''The Forum model'''

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100)

    body = models.TextField()

    author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="forums", blank=True, null=True)

    closed = models.BooleanField(default=False)
    updated = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    votes = GenericRelation(Vote, related_query_name="forum_vote")

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = unique_slug_generator(self.title, self.__class__)
            return super().save(*args, **kwargs)
        
        self.updated = True
        return super().save(*args, **kwargs)
    

apps/forums/forms.py
from django import forms
from forums.models import Forum


class ForumForm(forms.ModelForm):
    '''A form for creating Forums'''

    class Meta:
        model = Forum
        fields = fields = ("title", "body")

    def save(self, commit=True, author=None):
        forum = super().save(commit=False)
        forum.author = author
        forum.save()
        return forum

apps/forums/views/answers.py
from django.forms.models import BaseModelForm
from django.views.generic import ListView, View, UpdateView, DeleteView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from forums.models import ForumAnswer
from forums.mixins import ForumObject

def is_ajax(request):
    '''Check if a request is ajax or not'''
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class ForumAnswerCreateView(LoginRequiredMixin, ForumObject, View):
    def get(self, request, *args, **kwargs):
        return redirect("forums:forum-list")

    def post(self, request, *args, **kwargs):
        if is_ajax(request):
            object_id = request.POST.get('object_id')
            object_slug = request.POST.get('object_slug')
            content = request.POST.get('content')

            if object_id and object_slug and content:
                if self.forum.closed:
                    return JsonResponse({'closed':'forum is closed'})
                
                answer = ForumAnswer.objects.create(forum=self.forum, user=self.request.user, answer=content)
                # Create the comment here
                return JsonResponse({'created': 'answer created', 'date' : answer.date, 'answer' : answer.answer})
            
            return JsonResponse({'error':'invalid information'})
        
        return redirect("forums:forum-list")

class ForumAnswerListView(ForumObject, ListView):
    template_name = 'answers/forum-answer-list.html'
    context_object_name = 'answers'

    def get_queryset(self):
        return ForumAnswer.objects.select_related('user').filter(forum=self.forum).order_by('-is_correct_answer', '-date')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        content_type = ContentType.objects.get_for_model(ForumAnswer)
        context['model_content_type_id'] = content_type.id
        context['forum'] = self.forum
        return context


class ForumAnswerUpdateView(LoginRequiredMixin, ForumObject, UpdateView):
    
    template_name = 'answers/update-forum-answer.html'
    fields = ['answer']

    def get_object(self):
        return get_object_or_404(
            ForumAnswer, forum=self.forum, user=self.request.user,
            id=self.kwargs['answer_id'],
            token=self.kwargs['answer_token'],
        )
    
    def form_valid(self, form):
        messages.success(self.request, 'Answer Updated', 'success')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("forums:forum-answer-list", kwargs={"id" : self.forum.id, "slug" : self.forum.slug})


class ForumAnswerDeleteView(LoginRequiredMixin, ForumObject, DeleteView):
    
    template_name = 'answers/delete-forum-answer.html'

    def get_object(self):
        return get_object_or_404(
            ForumAnswer, forum=self.forum, user=self.request.user,
            id=self.kwargs['answer_id'],
            token=self.kwargs['answer_token'],
        )
    
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Answer Deleted!', 'danger')
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("forums:forum-answer-list", kwargs={"id" : self.forum.id, "slug" : self.forum.slug})


class ForumAnswerAcceptView(LoginRequiredMixin, ForumObject, UpdateView):
    
    template_name = 'answers/update-forum-answer.html'
    fields = ['is_correct_answer']

    def get_object(self):
        return get_object_or_404(
            ForumAnswer, forum=self.forum, forum__author=self.request.user.id,
            id=self.kwargs['answer_id'],
            token=self.kwargs['answer_token'],
        )
    
    def form_valid(self, form):
        messages.success(self.request, 'Answer updated', 'success')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("forums:forum-answer-list", kwargs={"id" : self.forum.id, "slug" : self.forum.slug})

apps/forums/views/forum.py
from django.views.generic import FormView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Count
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy

from ..forms import ForumForm
from forums.models import Forum
from accounts.models import Account


class ForumListView(LoginRequiredMixin, ListView):
    '''Show all newest forums'''
    template_name = "forums/forum-list.html"
    context_object_name = "forums"

    def get_queryset(self):
        forums = None
        user_token = self.request.GET.get('user')
        latest = self.request.GET.get('latest')
        title = self.request.GET.get('title')

        if user_token:
            # Get a users Forums
            user = get_object_or_404(Account, token=user_token)
            forums = user.forums.all()
        
        if latest:
            forums = Forum.objects.all().order_by('-date')

        # Filter article by its title
        if title:
            forums = Forum.objects.filter(title__icontains=title)

        else:
            forums = Forum.objects.all().annotate(
                vote_count=Count('votes')
            ).order_by('-vote_count')


        return forums.order_by('-closed')[:20]

class ForumDetailView(LoginRequiredMixin, DetailView):
    '''Detail page of forum'''

    template_name = "forums/forum-detail.html"

    def get_object(self):
        return get_object_or_404(Forum, id=self.kwargs['id'], slug=self.kwargs['slug'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_answers'] = self.get_object().answers.select_related('user').all().order_by('-is_correct_answer', '-date')[:5]
        return context


class ForumCreateView(LoginRequiredMixin, FormView):
    '''Create a new forum'''

    template_name = "forums/create-forum.html"
    form_class = ForumForm

    def form_valid(self, form):
        forum = form.save(commit=True, author=self.request.user)
        messages.success(self.request, 'Forum Created!', 'suceess')
        return redirect('forums:forum-detail', id=forum.id, slug=forum.slug)

    def form_invalid(self, form):
        messages.success(self.request, "Invalid information, try again.", "danger")
        return redirect("forums:create-forum")


class ForumUpdateView(LoginRequiredMixin, UpdateView):
    '''Update a forum (close or change price)'''

    template_name = "forums/update-forum.html"
    fields = ["title", "body", "closed"]

    def get_object(self):
        return get_object_or_404(Forum, id=self.kwargs["id"], slug=self.kwargs["slug"],
                                 author=self.request.user)

    def get_success_url(self):
        return reverse_lazy("forums:forum-detail", kwargs={"id": self.kwargs["id"],"slug": self.kwargs["slug"]})


class ForumDeleteView(LoginRequiredMixin, DeleteView):
    '''Delete a forum'''
    template_name = "forums/delete-forum.html"

    def get_object(self):
        k = self.kwargs
        return get_object_or_404(Forum, id=k["id"], slug=k["slug"],
                                 author=self.request.user)

    def get_success_url(self):
        return reverse_lazy("forums:forum-list")

apps/forums/templates/answers/create-forum-answer.html
{% load base_tags %}
{% load static %}
<input type="hidden" id="Answer-Url" data-url="{% url 'forums:create-forum-answer' object.id object.slug %}" />
<input type="hidden" id="CSRF" data="{{ csrf_token }}" />

<script src="{% static 'js/create_forum_answer.js' %}" type="text/javascript"></script>

{% if request.user.is_authenticated %}
    {% if object.closed %}
        <h4>Forum is closed, you cannot add any answers to it</h4>
    {% else %}
        <div class="input-group mb-3">
            <input type="text" name="body" id="id_answer" class="form-control" placeholder="Add Comment"  aria-describedby="basic-addon2">
            <div class="input-group-append">
            <button class="btn btn-outline-success" type="button" id="answer-submit"
            onclick="create_forum_answer({{object.id}}, '{{object.slug}}')">
                Submit
            </button>
            </div>
        </div>
    {% endif %}


{% else %}
    <a href={% url 'account_login' %}>Login to answer this object.</a>
{% endif %}

apps/forums/templates/answers/delete-forum-answer.html
{% extends 'base/_base.html' %}

{% block title %} Delete Forum answer {% endblock title %}


{% block body %}
    <h3>Delete `{{ object.answer }}`</h3>
    <br>

    <form method="post">
    {% csrf_token %}
        <h6>Dear {{ self.request.user }}, are you sure you want to <strong>delete</strong> this Answer?</h6>
        <p>This action cannot be undone.</p>
        <button class="btn btn-danger">Confirm Deletion</button>
    </form>
{% endblock body %}

apps/forums/templates/answers/forum-answer-list.html
{% extends 'base/_base.html' %}

{% block title %} Forum Answer List {% endblock title %}

{% block body %}
    <h1>{{ forum.title }}</h1>
    <hr>
        <div class="card-deck">
        {% for object in answers %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="card-text"><small class="text-muted">Answered by <a href='{% url 'accounts:profile' object.user.id object.user.token  %}'>{{ object.user.username }}</a> on {{ object.date }}</small> {% if object.is_correct_answer %}
                         <strong style="color: green;">Correct</strong>
                    {% endif %}</p>
                    {% if object.is_edited %}<small style='color: red;'>Edited</small>{% endif %}
                    <p class="card-text"> {{ object.answer }}</p>
                    {% if request.user == object.user %}
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'forums:update-forum-answer' forum.id forum.slug object.id object.token %}" class="btn btn-primary mr-2">Update</a>
                            <a href="{% url 'forums:delete-forum-answer' forum.id forum.slug object.id object.token %}" class="btn btn-danger">Delete</a>
                            {% if request.user == forum.author %}
                                {% if object.is_correct_answer %}
                                    <a href="{% url 'forums:accept-forum-answer' forum.id forum.slug object.id object.token %}" class="btn btn-danger">Mark as InCorrect</a>
                                {% else %}
                                    <a href="{% url 'forums:accept-forum-answer' forum.id forum.slug object.id object.token %}" class="btn btn-success">Mark as Correct</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                    
                </div>
            </div>
        {% empty %}
            <h3>No answers were found.</h3>
        {% endfor %}
    </div>
{% endblock body %}

apps/forums/templates/answers/update-forum-answer.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Update Forum Answer {% endblock title %}

{% block body %}
<h3>Update Forum answer</h3><br>
<form method="post"> {% csrf_token  %}

    {% for field in form %}
        {{ field | as_crispy_field }}<br>
    {% endfor %}

    <button class="btn btn-success">Update</button>
</form>

{% endblock body %}