apps/accounts/urls.py
from django.urls import path
from .views import ProfileView, ExchangeView

app_name = "accounts"

urlpatterns = [
    path("profile/<int:id>/<str:token>/", ProfileView.as_view(), name="profile"),
    path("exchange/", ExchangeView.as_view(), name="exchange"),
]

apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('', views.OrderListView.as_view(), name='order-list'),

    path("<int:id>/<str:token>/", views.OrderDetail.as_view(), name="order-detail"),

    path("<int:id>/<str:token>/create/", views.OrderCreateView.as_view(), name="create-order"),
    path("<int:id>/<str:token>/delete/", views.OrderDeleteView.as_view(), name="delete-order"),

    path("<int:id>/<str:token>/status/<str:status>/", views.OrderStatusView.as_view(), name="order-status"),

    path("<int:id>/<str:token>/pay/", views.OrderPayView.as_view(), name="pay-order"),
]

apps/products/urls.py
from django.urls import  path
from .views.product import (
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductDetailView,
)
from django.views.generic import RedirectView
from .views.category import ProductCategoryView

app_name = "products"

urlpatterns = [
    path("", RedirectView.as_view(url='/'), name="product-list"),

    path("<int:id>/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("create/", ProductCreateView.as_view(), name="create-product"),
    path("<int:id>/<str:slug>/update/", ProductUpdateView.as_view(), name="update-product"),
    path("<int:id>/<str:slug>/delete/", ProductDeleteView.as_view(), name="delete-product"),
    path("<int:id>/<str:slug>/category/", ProductCategoryView.as_view(), name="product-category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.products.views.product import ProductListView

THIRD_PARTY_URLS = [
    path("accounts/", include("allauth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

LOCAL_URLS = [
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("chats/", include("apps.chats.urls")),
    path("orders/", include("apps.orders.urls")),
    
    path("articles/", include("apps.articles.urls")),
    path("forums/", include("apps.forums.urls")),

    path("vote/", include("apps.votes.urls")),
    path("comments/", include("apps.comments.urls")),
]

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('admin/', admin.site.urls),

    *THIRD_PARTY_URLS,
    *LOCAL_URLS,


]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

handler404 = 'apps.orders.views.handler404'
handler500 = 'apps.orders.views.handler500'

apps/orders/models.py
from django.db import models
from products.models import Product
from accounts.models import Account
from orders.utils import unique_order_token_generator

class Order(models.Model):

    class STATUS(models.TextChoices):
        ORDERED = 'o', 'Ordered'
        ACCEPTED = 'a', 'Accepted'
        DECLINED = 'd', 'Declined'
        PREPARING = 'p', 'Preparing'
        SHIPPED = 's', 'Shipped'

    description = models.TextField(max_length=50, blank=True, null=True)
    token = models.CharField(max_length=20, unique=True, blank=True, null=True)

    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="orders", blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name="orders", blank=True, null=True)
    provider = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)

    price = models.PositiveIntegerField()
    status = models.CharField(max_length=1, choices=STATUS.choices, default=STATUS.ORDERED)

    is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.token)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.token = unique_order_token_generator(self.__class__)
            self.provider = self.product.provider
            self.price = self.product.price
            
        
        return super().save(*args, **kwargs)

apps/orders/views.py
from django.views.generic import View, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q
from django.db import transaction
from django.contrib import messages
from django.http import JsonResponse

from products.models import Product
from orders.models import Order

def is_ajax(request):
    '''Check if a request is ajax or not'''
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class OrderListView(LoginRequiredMixin, ListView):
    context_object_name = 'orders'

    def get_template_names(self):
        if self.request.GET.get('user', None) == 'me':
            return ['orders/order-list.html']
        else:
            return ['orders/customer-order-list.html']


    def get_queryset(self):
        if self.request.GET.get('user') == 'me':
            return Order.objects.filter(account=self.request.user)    
        
        return Order.objects.filter(provider=self.request.user).order_by('status')


class OrderCreateView(LoginRequiredMixin, View):
    """Create a new order with ajax"""

    def post(self, request, *args, **kwargs):
        if not is_ajax(request):
            return JsonResponse({"error": "This is not an ajax request."})

        object_id = request.POST.get("object_id")
        object_slug = request.POST.get("object_slug")
        quantity = request.POST.get("quantity")

        if not all([object_id, object_slug, quantity]):
            return JsonResponse({"error": "Information is incomplete."})

        description = request.POST.get("description", None)

        # Get the product that user wants to order
        product = get_object_or_404(Product, id=object_id, slug=object_slug)

        if not product.is_available:
            return JsonResponse({"error": "Product is not available."})

        # Update older order if there is one created
        order = Order.objects.filter(account=request.user, product=product, status="o").first()
        if order:
            order.description = description
            order.quantity = quantity
            order.save()
            return JsonResponse({"success": "An older order has been updated."})

        # Create a new order
        order = Order.objects.create(
            account=request.user,
            product=product,
            quantity=quantity,
            description=description,
            price=product.price,
        )

        return JsonResponse({"success": "Order has been created."})
        

class OrderStatusView(View):
    '''
    Accept/Reject an order
    Also change objects status to Shipped
    '''

    def get_object(self, id, token):
        return get_object_or_404(Order, id=id, token=token, product__provider=self.request.user)

    def get(self, request, id, token, status, *args, **kwargs):
        
        obj = self.get_object(id, token)

        if obj.status == 'o' and status in ['a', 'r']:
            obj.status = status
            obj.save()
            messages.success(request, f'Order request changed to {obj.get_status_display()}', 'success')

        elif obj.status == 'p' and status == 's':
            obj.status = status
            obj.save()
            messages.success(request, f'Order request changed to {obj.get_status_display()}', 'success')

        else:
            messages.error(request, 'Invalid status for this object.', 'danger')

        return redirect('orders:order-list')


class OrderDetail(LoginRequiredMixin, DetailView):
    '''Detail page of an order.'''

    template_name = "orders/order-detail.html"
    context_object_name = "order"

    def get_object(self):
        return get_object_or_404(Order, Q(id=self.kwargs["id"]) & Q(token=self.kwargs["token"]),
                                Q(account=self.request.user) | Q(product__provider=self.request.user))


class OrderDeleteView(LoginRequiredMixin, DeleteView):
    '''Delete orders that vendor have not seen them'''

    template_name = "orders/delete-order.html"
    context_object_name = "order"
    success_url = '/'

    def get_object(self):
        return get_object_or_404(Order, id=self.kwargs['id'], token=self.kwargs['token'],
                                account=self.request.user, status='o')


class OrderPayView(LoginRequiredMixin, View):
    """Pay for an order"""

    template_name = "orders/pay-order.html"

    def get_object(self, id, token):
        return get_object_or_404(
            Order,
            id=id,
            token=token,
            account=self.request.user,
            status="a",
            product__is_available=True,
        )

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object(
            self.kwargs["id"], self.kwargs["token"]
        )
        # redirect user to exchange page if user doesnt have enough money
        if request.user.balance < self.object.price:
            messages.success(
                self.request,
                "You dont have enough money, first charge your wallet.",
                "danger",
            )
            return redirect("accounts:exchange")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(
            request,
            self.template_name,
            {"order": self.get_object(self.kwargs["id"], self.kwargs["token"])},
        )

    @transaction.atomic
    def post(self, request, id, token):
        order = self.get_object(id, token)

        self.request.user.balance -= order.price
        order.product.provider.balance += order.price
        order.status = "p"
        order.is_paid = True

        order.product.provider.save()
        self.request.user.save()
        order.save()

        messages.success(
            self.request,
            "Order successfully got paid, want for provider to prepare it.",
            "success",
        )
        return redirect("orders:order-detail", id=order.id, token=order.token)


# error handling functions
def handler404(request, exception):
    return render(request, "base/error/404.html")

def handler500(request, *args, **argv):
    return render(request, "base/error/500.html")

apps/orders/templates/orders/add-order.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Add Order {% endblock title %}


{% block body %}
    <h3>Add Order</h3>

    <form method="post"> {% csrf_token %}

        {{ form.description | as_crispy_field }} <br>

        <button class="btn btn-success">Add order</button>
    </form>

{% endblock body %}

apps/orders/templates/orders/customer-order-list.html
{% extends 'base/_base.html' %}

{% block title %} Customer Order List {% endblock title %}

{% block body %}

    <h2>Customer Order List</h2><br>

    <table class="table">
        <thead>
            <tr>
                <th>Order</th>
                <th>Product</th>
                <th>Status</th>
                <th>Account</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td><a href="{% url 'orders:order-detail' order.id order.token %}">{{ order.token }}</a></td>
                    <td><a href="{% url 'products:product-detail' order.product.id order.product.slug %}">{{ order.product }}</a></td>
                    <td>{{ order.get_status_display }}</td>
                    <td><a href="{% url 'accounts:profile' order.account.id order.account.token %}">{{ order.account }}</a></td>
                    <div class="col-sm">
                        {% if order.status == "o" %}
                        <td>
                            <a href="{% url 'orders:order-status' order.id order.token 'a' %}" class="btn btn-success">Accept</a>
                            <a href="{% url 'orders:order-status' order.id order.token 'r' %}" class="btn btn-danger">Decline</a>
                        </td>
                        
                        {% elif order.status == "p" %}
                        <td><a href="{% url 'orders:order-status' order.id order.token 's' %}" class="btn btn-secondary">Shipped</a></td>
                        {% elif order.status == "a" %}
                            <td>Wait for user payment</td>
                        {% endif %}
                    </div>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No order available</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock body %}

apps/orders/templates/orders/delete-order.html
{% extends 'base/_base.html' %}

{% block title %} Delete Order {% endblock title %}


{% block body %}
    <h3>Delete Order</h3>

    <form method="post"> {% csrf_token %}
        <br><h5>Are you sure that you want to delete {{ order.product }}'s order??</h5>
        <br>

        <button class="btn btn-danger">Yes, delete it.</button>
    </form>

{% endblock body %}

apps/orders/templates/orders/order-detail.html
{% extends 'base/_base.html' %}

{% block title %}Order Detail{% endblock title %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-8">
                <div class="card">
                    <h5 class="card-header">Order Token: {{ order.token }}</h5>
                <div class="card-body">
                    <h6>Item: <a href="{% url 'products:product-detail' order.product.id order.product.slug %}">{{ order.product }}</a></h6>
                <hr>
                    <h6>Status: {{ order.get_status_display }}</h6>
                <hr>
                    <h6>Price: {{ order.price }}</h6>
                <hr>
                    <h6>Account: <a href="{% url 'accounts:profile' order.account.id order.account.token %}">{{ order.account }}</a></h6>
                <hr>
                    <h6>Description:</h6>
                    <p>{{ order.description }}</p>
                <hr>

                {% if request.user == order.product.provider %}
                    {% if order.status == "o"  %}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'orders:order-status' order.id order.token 'a' %}" class="btn btn-success me-md-2" role="button">Accept</a>
                            <a href="{% url 'orders:order-status' order.id order.token 'r' %}" class="btn btn-danger" role="button">Decline</a>
                        </div>
                    {% endif %}
                    {% if order.status == "p" %}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'orders:order-status' order.id order.token 's' %}" class="btn btn-secondary me-md-2" role="button">Shipped</a>
                        </div>
                    {% endif %}
                {% endif %}

                {% if request.user == order.account %}
                    {% if order.status == 'o'  %}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'orders:delete-order' order.id order.token %}" class="btn btn-danger" role="button">Delete Order</a>
                        </div>
                    {% endif %}

                    {% if order.status == 'a' and order.product.is_available %}

                        <div class="d-grid ">
                            <p>Order is accepted, pay for prepreation.</p><br>
                            <a href="{% url 'orders:pay-order' order.id order.token %}" class="btn btn-secondary" role="button">Pay</a>
                        </div>
                    {% endif %}
                {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

apps/orders/templates/orders/order-list.html
{% extends 'base/_base.html' %}

{% block title %} Order List {% endblock title %}

{% block body %}

    <h2>Order List</h2><br>

    <table class="table">
        <thead>
            <tr>
                <th>Order</th>
                <th>Product</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td><a href="{% url 'orders:order-detail' order.id order.token %}">{{ order.token }}</a></td>
                    <td><a href="{% url 'products:product-detail' order.product.id order.product.slug %}">{{ order.product }}</a></td>
                    <td>{{ order.get_status_display }}</td>
                    <div class="col-sm">
                        {% if order.status == "o" %}
                        <td>
                            <a href="{% url 'orders:delete-order' order.id order.token %}" class="btn btn-danger">Delete</a>
                        </td>
                        
                        {% elif order.status == "p" %}
                            <td>Item is preparing</td>
                        {% elif order.status == "a" %}
                            <td><a href="{% url 'orders:pay-order' order.id order.token %}" class="btn btn-primary">Pay</a></td>
                        {% else %}
                            <td><p>Item is shipped.</p></td>
                        {% endif %}
                    </div>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No order available</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock body %}

apps/orders/templates/orders/pay-order.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Pay Order {% endblock title %}


{% block body %}
    <h3>Pay</h3>
    <p>Are you sure you want to pay {{ order.price }} coins for 
        <a href="{% url 'orders:order-detail' order.id order.token %}">{{ order.product }}</a>?</p>

    <form method="post"> {% csrf_token %}
        <button class="btn btn-success">Yes, Continue.</button>
    </form>

{% endblock body %}

apps/orders/templates/orders/product-search.html
{% extends 'base/_base.html' %}

{% block title %}  Result {% endblock title %}


{% block body %}

    {% for product in products %}
            <div class="card" style="width: 15rem mb-4; display:inline-block;">
                  {% if product.picture %}
                    <img class="card-img-top" src="{{ product.picture.url }}" alt="Card image cap" width="70px;" height="250px;">
                  {% endif %}

                  <div class="card-body">
                      <a href="{% url 'products:product-detail' product.id product.slug %}"> <p class="card-text">{{ product.title }}</p> </a>
                      <hr>
                      <p class="card-text">©{{ product.price }}</p>
                  </div>
            </div>
        {% empty %}
            <h6>No result available.</h6>
        {% endfor %}

{% endblock body %}