apps/accounts/urls.py
from django.urls import path
from .views import ProfileView, ExchangeView

app_name = "accounts"

urlpatterns = [
    path("profile/<int:id>/<str:token>/", ProfileView.as_view(), name="profile"),
    path("exchange/", ExchangeView.as_view(), name="exchange"),
]

apps/articles/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article-list"),

    path("create/", views.ArticleCreateView.as_view(), name="create-article"),
    
    path("<int:id>/<str:slug>/update/", views.UpdateArticle.as_view(), name="update-article"),
    path("<int:id>/<str:slug>/delete/", views.DeleteArticle.as_view(), name="delete-article"),

    path("<int:id>/<str:slug>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("<int:id>/<str:slug>/purchase/", views.ArticlePurchaseView.as_view(), name="purchase-article"),


]

apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('', views.OrderListView.as_view(), name='order-list'),

    path("<int:id>/<str:token>/", views.OrderDetail.as_view(), name="order-detail"),

    path("<int:id>/<str:token>/create/", views.OrderCreateView.as_view(), name="create-order"),
    path("<int:id>/<str:token>/delete/", views.OrderDeleteView.as_view(), name="delete-order"),

    path("<int:id>/<str:token>/status/<str:status>/", views.OrderStatusView.as_view(), name="order-status"),

    path("<int:id>/<str:token>/pay/", views.OrderPayView.as_view(), name="pay-order"),
]

apps/products/urls.py
from django.urls import  path
from .views.product import (
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductDetailView,
)
from django.views.generic import RedirectView
from .views.category import ProductCategoryView

app_name = "products"

urlpatterns = [
    path("", RedirectView.as_view(url='/'), name="product-list"),

    path("<int:id>/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("create/", ProductCreateView.as_view(), name="create-product"),
    path("<int:id>/<str:slug>/update/", ProductUpdateView.as_view(), name="update-product"),
    path("<int:id>/<str:slug>/delete/", ProductDeleteView.as_view(), name="delete-product"),
    path("<int:id>/<str:slug>/category/", ProductCategoryView.as_view(), name="product-category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.products.views.product import ProductListView

THIRD_PARTY_URLS = [
    path("accounts/", include("allauth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

LOCAL_URLS = [
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("chats/", include("apps.chats.urls")),
    path("orders/", include("apps.orders.urls")),
    
    path("articles/", include("apps.articles.urls")),
    path("forums/", include("apps.forums.urls")),

    path("vote/", include("apps.votes.urls")),
    path("comments/", include("apps.comments.urls")),
]

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('admin/', admin.site.urls),

    *THIRD_PARTY_URLS,
    *LOCAL_URLS,


]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

handler404 = 'apps.orders.views.handler404'
handler500 = 'apps.orders.views.handler500'

apps/orders/models.py
from django.db import models
from products.models import Product
from accounts.models import Account
from orders.utils import unique_order_token_generator

class Order(models.Model):

    class STATUS(models.TextChoices):
        ORDERED = 'o', 'Ordered'
        ACCEPTED = 'a', 'Accepted'
        DECLINED = 'd', 'Declined'
        PREPARING = 'p', 'Preparing'
        SHIPPED = 's', 'Shipped'

    description = models.TextField(max_length=50, blank=True, null=True)
    token = models.CharField(max_length=20, unique=True, blank=True, null=True)

    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="orders", blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name="orders", blank=True, null=True)
    provider = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)

    price = models.PositiveIntegerField()
    status = models.CharField(max_length=1, choices=STATUS.choices, default=STATUS.ORDERED)

    is_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.token)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.token = unique_order_token_generator(self.__class__)
            self.provider = self.product.provider
            self.price = self.product.price
            
        
        return super().save(*args, **kwargs)

apps/products/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from django_countries.fields import CountryField

from accounts.models import Account
from votes.models import Vote
from comments.models import Comment
from products.utils import unique_slug_generator


class Product(models.Model):

    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    picture = models.ImageField(upload_to="products/%Y-%m-%d", blank=True, null=True)

    category = models.ForeignKey("Category", on_delete=models.SET_NULL, related_name="products", blank=True, null=True)
    shipping_origin = CountryField()
    shipping_destinations = CountryField(blank=True, null=True)
    
    provider = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True, related_name="products")

    price = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=False)

    votes = GenericRelation(Vote, related_query_name="product_vote")
    comments = GenericRelation(Comment, related_query_name="product_comment")

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        
        # When user changes the title, slug will be updated too.
        if not self.slug or slugify(self.title) not in self.slug:
            self.slug = unique_slug_generator(title=self.title, cls=self.__class__)

        return super().save(*args, **kwargs)


class Category(models.Model):

    parent = models.ForeignKey(
        'self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children'
    )
    
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        self.slug = unique_slug_generator(self.title, self.__class__)
        return super().save(*args, **kwargs)

apps/products/forms.py
from django import forms
from products.models import Product, Category

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'picture',
            'price',
            'shipping_origin',
            'shipping_destinations',
            'is_available',
            
        ]

class CategoryForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Category.objects.filter(parent=None), required=False)
    class Meta:
        model = Category
        fields = ['title', 'parent']

    def save(self, instance):

        category = None

        if self.cleaned_data['title']:
            # get or create the category
            category, created = Category.objects.get_or_create(
                title=self.cleaned_data['title'].lower(), parent=self.cleaned_data['parent']
            )

        else:
            self.cleaned_data['parent']  = category

        # if category already is assigned to the object, it will remove it
        if category == instance.category:
            instance.category = None

        # othervise add the category for the object
        else:
            instance.category = category

        instance.save()


        

apps/products/views/category.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from products.models import Product
from products.forms import CategoryForm


class ProductCategoryView(LoginRequiredMixin, View):
    '''List of a products categories and add/remove an item.'''
    
    template_name = 'category/product-category.html'
    
    def get_object(self):
        return get_object_or_404(Product, provider=self.request.user, id=self.kwargs['id'], slug=self.kwargs['slug'])

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        return render(request, self.template_name, {'object_category' : obj.category, 'form' : CategoryForm()})

    def post(self, request, *args, **kwargs):
        obj = self.get_object()

        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(instance=obj)
            messages.success(request, 'Category added for item.', 'success')
            return redirect('products:product-detail', id=obj.id, slug=obj.slug)
        
        messages.success(request, 'Invalid information.', 'danger')
        return redirect('products:product-detail', id=obj.id, slug=obj.slug)

apps/products/views/product.py
from django.views.generic import UpdateView, DeleteView, DetailView, ListView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q
from django.urls import reverse_lazy

from products.models import Product, Category
from ..forms import ProductForm


class ProductListView(LoginRequiredMixin, ListView):
    '''Show all products, if there is any param given, give the users products'''

    template_name = "products/product-list.html"
    context_object_name = "products"

    def get_queryset(self):
        queryset = Product.objects.all().order_by('-is_available')

        username = self.request.GET.get('username')
        title = self.request.GET.get('title')
        category_title = self.request.GET.get('category')

        if username:
            queryset = queryset.filter(provider__username=username)
        elif title:
            queryset = queryset.filter(title=title)
        elif category_title:
            category = get_object_or_404(Category, title=category_title)
            queryset = category.products.all()

        return queryset.order_by('-is_available')        


class ProductCreateView(LoginRequiredMixin, FormView):
    '''A view for creating products'''

    form_class = ProductForm
    template_name = 'products/create-product.html'

    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES)
        data = form.save(commit=False)
        data.provider = self.request.user
        data.save()
        messages.success(self.request, "Product added successfully.", "success")
        return redirect("products:product-list")


    def form_invalid(self, form):
        messages.success(self.request, "Invalid information were given.", "danger")
        return redirect("products:product-list")

class ProductDetailView(DetailView):
    '''Return detail of a product'''

    template_name = "products/product-detail.html"
    context_object_name = "product"

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs["id"], slug=self.kwargs["slug"])


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    '''Update page of a product'''

    template_name = "products/update-product.html"
    fields = ["title", "description", "picture", "shipping_origin",
              "shipping_destinations", "price", "is_available"]
    context_object_name = "product"

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs["id"],
                                 slug=self.kwargs["slug"],
                                 provider=self.request.user)
    
    def get_success_url(self):
        return reverse_lazy("products:product-detail",
                             kwargs={"id": self.kwargs["id"],
                                     "slug": self.kwargs["slug"]})
    

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    '''Delete a product by its provider'''

    template_name = "products/delete-product.html"
    context_object_name = "product"
    success_url = reverse_lazy("products:product-list")

    def dispatch(self, request, *args, **kwargs):

        if (obj:=self.get_object()).orders.filter(~Q(status='s')):

            messages.success(
                request, 
                'Sorry, you cannot delete this product as it has associated orders that need to be shipped.', 
                'danger'
                )
            return redirect('products:product-detail', id=obj.id, slug=obj.slug)
        
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs["id"],
                                 slug=self.kwargs["slug"],
                                 provider=self.request.user)
    

apps/products/templates/products/create-product.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Create Product {% endblock title %}


{% block body %}
    <h3>Fill out this form</h3> <br>

    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
        {{ form.title | as_crispy_field }} <br>
        {{ form.description | as_crispy_field }} <br>
        {{ form.picture | as_crispy_field }} <br>
        {{ form.price | as_crispy_field }} <br>
        {{ form.is_available | as_crispy_field }} <br>
        {{ form.shipping_origin | as_crispy_field }} <br>
        {{ form.shipping_destinations | as_crispy_field }} <br>


        <button class="btn btn-success">Save</button>
    </form>


{% endblock body %}

apps/products/templates/products/delete-product.html
{% extends 'base/_base.html' %}

{% block title %} Delete {{ object.title }} {% endblock title %}


{% block body %}
    <h3>Delete {{ object.title }}</h3>
    <br>

    <form method="post">
    {% csrf_token %}
        <h6>Dear {{ object.provider }}, are you sure you want to <strong>delete</strong> this product?</h6>
        <p>This action cannot be undone.</p>
        <br>
        <button class="btn btn-danger">Confirm Deletion</button>
    </form>
{% endblock body %}

apps/products/templates/products/product-detail.html
{% extends 'base/_base.html' %}
{% load static %}


{% block title %} {{product.title}} {% endblock title %}


{% block body %}
<div class="row no-gutters">
            <div id="message"></div>
    
            <input type="hidden" id="CREATE_ORDER_URL" data-url="{% url 'orders:create-order' object.id object.slug%}" />
            <input type="hidden" id="CSRF" data="{{ csrf_token }}" />
            <div class="col-auto">
                {% if product.picture %}
                        <img src="{{ product.picture.url }}" width="470px;" height="470px" class="rounded float-left">
                {% else %}
                    <h3>No picture were provided.</h3>
                {% endif %}
            </div>

            <div class="col">
                <div class="card-block px-2">

                    <h4 class="card-title">{{ product.title }}</h4> <br>

                    {% if product.is_available %}
                        <p class="card-text" style="color:red;">Price: ©{{ product.price }}</p>
                    {% endif %}

                    <div class="shadow-none p-3 mb-5 bg-light rounded">
                        <p>provider: <a href="{% url 'accounts:profile' product.provider.id product.provider.token %}">{{ product.provider }}</a></p>

                        {% if  product.shipping_origin %}
                            <p>Ship from: {{ product.shipping_origin.unicode_flag }} {{ product.shipping_origin.code }}</p>
                        {% else %}
                            <p style="color:red;">No origin country were given, ask it from the provider.</p>
                        {% endif %}

                        {% if  product.shipping_destinations %}
                            <p>Ship from: {{ product.shipping_destinations.unicode_flag }} {{ product.shipping_destinations.code }}</p>
                        {% else %}
                            <p>World wide.</p>
                        {% endif %}

                        {% if  product.category %}
                            <p>Category: <a href="{% url 'products:product-list' %}?category={{product.category}}">{{ product.category.parent }} | {{ product.category }}</a></p>
                        {% endif %} 
                        {% if request.user == product.provider %}
                        <a href="{% url 'products:product-category' product.id product.slug %}" class="btn btn-secondary">
                            Category Setting
                        </a>
                        <a href="{% url 'products:update-product' product.id product.slug %}" class="btn btn-secondary">
                            Update Product
                        </a>
                        <a href="{% url 'products:delete-product' product.id product.slug %}" class="btn btn-danger">
                            Delete Product
                        </a>

                        {% endif %}
                        
                        {% if  request.user != product.provider %}
                            {% if product.is_available %}
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#orderInformationModal">
                                Add Order
                            </button>
                            
                            <div class="modal fade" id="orderInformationModal" tabindex="-1" role="dialog" aria-labelledby="orderInformationModalTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Order Information</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">

                                        <label for="product-quantity" class="col-form-label">Quantity:</label>
                                        <input type="text" class="form-control" id="id_quantity" required>
                                        <label for="product-quantity" class="col-form-label">Description:</label>
                                        <input type="text" class="form-control" id="id_description">

                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-success"  data-dismiss="modal" onclick="create_order({{object.id}}, '{{object.slug}}')">
                                        Confirm
                                    </button>
                                    </div>
                                </div>
                                </div>
                            </div>
                            {% else %}
                                <p style="color:red;">This item is unavailable.</p>
                            {% endif %}
                        {% endif %}
                        <hr>
                        {% include "vote/vote.html" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer w-100 text-muted">
            <hr>
            <h3>Description</h3>
            <p>{{ product.description }}</p>
        </div>
        <div class="card-footer w-100 text-muted">
            <hr>
            <h3>Comments</h3>
            {% include "comments/comment.html" %}
        </div>
        <div class="card-footer w-100 text-muted">
            <hr>
            <h5><a class="dropdown-item" href="{% url 'article:article-list' %}?product={{product.slug}}">Product Articles</a></h5>
        </div>

        <script src="{% static 'js/create_order.js' %}" type="text/javascript"></script>

{% endblock body %}

apps/products/templates/products/product-list.html
{% extends 'base/_base.html' %}


{% block title %} Product List {% endblock title %}


{% block body %}
    <div class="form-outline">
        <form action="{{ request.get_full_path }}" method="GET">
            <input type="search" name="title" class="form-control" placeholder="Search For Product" aria-label="Search" />
        </form>
    </div><br>
    {% for product in products %}

            <div class="card" style="width: 15rem; display:inline-block;">

                  {% if product.picture %}
                    <img class="card-img-top" src="{{ product.picture.url }}" alt="Card image cap" width="70px;" height="250px;">
                  {% endif %}

                  <div class="card-body">
                      <a href="{% url 'products:product-detail' product.id product.slug %}"> <p class="card-text">{{ product.title }}</p> </a>
                      <hr>
                      <p class="card-text">©{{ product.price }} | {% if product.is_available %} &#x2713;{% else %}×{% endif %}
                      </p>
                  </div>
            </div>
        {% empty %}
            <h6>Oh, Nothig found in our database...</h6>
        {% endfor %}

{% endblock body %}

apps/products/templates/products/update-product.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Update "{{product.title}}"{% endblock title %}


{% block body %}
    <h3>Update page for "{{ product.title }}"</h3> <br>

    <form method="post" enctype="multipart/form-data"> {% csrf_token %}

        {{ form.title | as_crispy_field }} <br>
        {{ form.description | as_crispy_field }} <br>
        {{ form.picture | as_crispy_field }} <br>
        {{ form.shipping_origin | as_crispy_field }} <br>
        {{ form.shipping_destinations | as_crispy_field }} <br>
        {{ form.price | as_crispy_field }} <br>
        {{ form.is_available | as_crispy_field }}

        <br><button class="btn btn-success">Save</button>
    </form>

{% endblock body %}