apps/accounts/urls.py
from django.urls import path
from .views import ProfileView, ExchangeView

app_name = "accounts"

urlpatterns = [
    path("profile/<int:id>/<str:token>/", ProfileView.as_view(), name="profile"),
    path("exchange/", ExchangeView.as_view(), name="exchange"),
]

apps/comments/urls.py
from django.urls import path
from . import views

app_name = "comments"

urlpatterns = [
    path("add/", views.AddCommentView.as_view(), name="add-comment"),
    path("<int:content_type_id>/<object_id>/list/", views.CommentListView.as_view(), name='comment-list'),
    path("<int:comment_id>/update/", views.CommentUpdateView.as_view(), name='update-comment'),
    path("<int:comment_id>/delete/", views.CommentDeleteView.as_view(), name="delete-comment"),
    path("<int:comment_id>/", views.CommentDetailView.as_view(), name="comment-detail")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.products.views.product import ProductListView

THIRD_PARTY_URLS = [
    path("accounts/", include("allauth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

LOCAL_URLS = [
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("chats/", include("apps.chats.urls")),
    path("orders/", include("apps.orders.urls")),
    
    path("articles/", include("apps.articles.urls")),
    path("forums/", include("apps.forums.urls")),

    path("vote/", include("apps.votes.urls")),
    path("comments/", include("apps.comments.urls")),
]

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('admin/', admin.site.urls),

    *THIRD_PARTY_URLS,
    *LOCAL_URLS,


]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

handler404 = 'apps.orders.views.handler404'
handler500 = 'apps.orders.views.handler500'

apps/comments/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.db import models

from votes.models import Vote


class Comment(models.Model):
    
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, 
                            related_name="comments")

    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True,
                                related_name="replies")   

    date = models.DateTimeField(auto_now_add=True)                                
    body = models.TextField()

    is_edited = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    votes = GenericRelation(Vote)


    def __str__(self) -> str:
        return str(self.user)

    def save(self, *args, **kwargs):
        if self.pk:
            self.is_edited = True
        return super().save(*args, **kwargs)
    

apps/comments/views.py
from typing import Any, Dict
from django.views.generic import View, ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse_lazy
from django.contrib import messages
from comments.models import Comment
from comments.mixins import ObjectMixin

def is_ajax(request):
    '''Check if a request is ajax or not'''
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class AddCommentView(LoginRequiredMixin, View):
    '''Add a comment for an object'''

    def get(self, request):
        return redirect("product-list")

    def post(self, request):
        if not is_ajax(request):
            return redirect("product-list")
        parent_id = request.POST.get('parent_id')
        object_id = request.POST.get('object_id')
        content_type_id = request.POST.get('content_type_id')
        body = request.POST.get('body')

        if not all([object_id, content_type_id, body]):
            return JsonResponse({'error': 'invalid information'})
        
        if parent_id:
            # Reply if there is any parent id.
            parent_comment = get_object_or_404(Comment, id=parent_id)
            comment = Comment.objects.create(
                user=request.user,
                body=body,
                content_object=parent_comment,
                parent=parent_comment
            )
            response_data = {
            'created': {
                'user': comment.user.username,
                'body': comment.body,
                'date': comment.date
                }
            }
            return JsonResponse(response_data)
            

        content_type = get_object_or_404(ContentType, id=content_type_id)
        obj = get_object_or_404(content_type.model_class(), id=object_id)

        comment = Comment.objects.create(
            user=request.user,
            body=body,
            content_object=obj
        )

        response_data = {
            'created': {
                'user': comment.user.username,
                'body': comment.body,
                'date': comment.date
            }
        }

        return JsonResponse(response_data)
    
class CommentListView(ObjectMixin, ListView):
    template_name = 'comments/comment-list.html'
    context_object_name = 'comments'

    def get_queryset(self):
        return self.object.comments.select_related('user').all().order_by('-votes')

class CommentDetailView(LoginRequiredMixin, DetailView):
     template_name = 'comments/comment-detail.html'
     context_object_name = 'comment'

     def get_object(self):
          return get_object_or_404(Comment.objects.select_related('user'), id=self.kwargs['comment_id'])
     
     def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['replies'] = self.get_object().replies.select_related('user').all().order_by('-date')
        return context

class CommentUpdateView(LoginRequiredMixin, UpdateView):
    '''Update a comment by its writer'''

    template_name = 'comments/update-comment.html'
    fields = ['body']

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['comment_id'], user=self.request.user)
    
    def get_success_url(self) -> str:
        return reverse_lazy("comments:comment-detail", kwargs={"comment_id" : self.kwargs["comment_id"]})
    
    def post(self, request, *args, **kwargs):
            messages.success(request, 'Comment updated.', 'success')
            return super().post(request, *args, **kwargs)

    

class CommentDeleteView(LoginRequiredMixin, DeleteView):
        template_name = 'comments/delete-comment.html'
        success_url = '/'

        def get_object(self):
            return get_object_or_404(Comment, id=self.kwargs['comment_id'], user=self.request.user)
        
        def post(self, request, *args, **kwargs):
            messages.success(request, 'Comment deleted.', 'danger')
            return super().post(request, *args, **kwargs)

apps/comments/templates/comments/comment-detail.html
{% extends 'base/_base.html' %}

{% block title %}Comment Detail{% endblock title %}

{% block body %}
    
  <input type="hidden" id="parentCommentID" data-url="{{comment.id}}" />
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title"><a href="{% url 'accounts:profile' comment.user.id comment.user.token %}">{{ comment.user }}</a></h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ comment.date }}</h6>
      {% if comment.is_edited %}
      <span class="badge badge-pill badge-danger mb-2">Edited</span>
      {% endif %}
      <p class="card-text">{{ comment.body }}</p>
      {% if request.user == comment.user %}
      <div class="d-flex justify-content-end">
        <a href="{% url 'comments:update-comment' comment.id %}" class="btn btn-primary mr-2">Edit</a>
        <a href="{% url 'comments:delete-comment' comment.id %}" class="btn btn-danger">Delete</a>
      </div> <br>
      {% endif %}
      {% include "vote/vote.html" %}
    </div>
  </div>
  
  <hr>
  
  <h3>Replies</h3>
  {% include 'comments/create-comment.html' %}
  {% if replies %}
    <div class="container">
      <div class="row">
          <div class="col-md-12">
              <div class="card my-4">
                  <h3 class="card-header text-center">Comments</h3>
                  <div class="card-body">
                      <ul class="list-unstyled" id="comment-list">
                      {% for reply in replies %}
                          <li class="media my-4">
                              <div class="media-body">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <h5 class="mt-0 comment-user">{{ reply.user }}</h5>
                                          <p class="comment-date">{{ reply.date }}</p>
                                      </div>
                                  </div>
                                  <a href="{% url 'comments:comment-detail' reply.id %}"><p class="mb-0">{{ reply.body }}</p></a>
    
                              </div>
                          </li>
                      {% empty %}
                          No comment available
                      {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
      </div>
    </div>
  {% endif %}
  
{% endblock body %}

apps/comments/templates/comments/comment-list.html
{% extends 'base/_base.html' %}

{% block title %} Comment List{% endblock title %}

{% block body %}
    <div class="card-deck">
        {% for comment in comments %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="card-text"><small class="text-muted">Answered by <a href='{% url 'accounts:profile' comment.user.id comment.user.token  %}'>{{ comment.user.username }}</a> on {{ comment.date }}</small> 
                    </p>
                    {% if comment.is_edited %}<small style='color: red;'>Edited</small>{% endif %}
                    <a href="{% url 'comments:comment-detail' comment.id %}"><p class="card-text"> {{ comment.body }}</p></a>
                    {% if request.user == comment.user %}
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'comments:update-comment' comment.id %}" class="btn btn-primary mr-2">Update</a>
                            <a href="{% url 'comments:delete-comment' comment.id %}" class="btn btn-danger">Delete</a>
                        </div>
                    {% endif %}
                    
                </div>
            </div>
        {% empty %}
            <h3>No comments were found.</h3>
        {% endfor %}
    </div>
{% endblock body %}

apps/comments/templates/comments/comment.html
{% load base_tags %}
{% include 'comments/create-comment.html' %}

{% include 'comments/top-comment-list.html' %}


<a href="{% url 'comments:comment-list' object|get_model_content_type_id object.id %}" id="show-comments-link">Show all comments</a>

apps/comments/templates/comments/create-comment.html
{% load base_tags %}
{% load static %}

<input type="hidden" id="Comment-Url" data-url="{% url 'comments:add-comment' %}" />
<input type="hidden" id="CSRF" data="{{ csrf_token }}" />

<script src="{% static 'js/create_comment.js' %}" type="text/javascript"></script>

{% if request.user.is_authenticated %}
    <div class="input-group mb-3">
        <input type="text" name="body" id="id_comment" class="form-control" placeholder="Add Comment"  aria-describedby="basic-addon2">
        <div class="input-group-append">
        <button class="btn btn-outline-success" type="button" id="comment-submit"
        onclick="add_comment({{object.id}})">
            Submit
        </button>
        </div>
    </div>


{% else %}
    <a href={% url 'account_login' %}>Login to comment this object.</a>
{% endif %}

apps/comments/templates/comments/delete-comment.html
{% extends 'base/_base.html' %}

{% block title %} Delete Comment {% endblock title %}


{% block body %}
    <h3>Delete `{{ object.body }}`</h3>
    <br>

    <form method="post">
    {% csrf_token %}
        <h6>Dear {{ self.request.user }}, are you sure you want to <strong>delete</strong> this comment?</h6>
        <p>This action cannot be undone.</p>
        <button class="btn btn-danger">Confirm Deletion</button>
    </form>
{% endblock body %}

apps/comments/templates/comments/top-comment-list.html
{% load comment_tags %}
{% load base_tags %}
{% load static %}

<style>
.comment-user {
    display: inline-block;
    font-weight: bold;
}

.comment-date {
    display: inline-block;
    margin-left: 10px;
    font-size: 14px;
    color: #999;
}
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <h3 class="card-header text-center">Comments</h3>
                <div class="card-body">
                    <ul class="list-unstyled" id="comment-list">
                    {% for comment in object|get_object_top_comments %}
                        <li class="media my-4">
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h5 class="mt-0 comment-user">{{ comment.user }}</h5>
                                        <p class="comment-date">{{ comment.date }}</p>
                                    </div>
                                </div>
                                <a href="{% url 'comments:comment-detail' comment.id %}"><p class="mb-0">{{ comment.body }}</p></a>

                            </div>
                        </li>
                    {% empty %}
                        No comment available
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

apps/comments/templates/comments/update-comment.html
{% extends 'base/_base.html' %}
{% load crispy_forms_tags %}

{% block title %} Update Comment {% endblock title %}

{% block body %}
<h3>Update the comment</h3><br>

<form method="post"> {% csrf_token  %}

    {% for field in form %}
        {{ field | as_crispy_field }}<br>
    {% endfor %}

    <button class="btn btn-success">Update</button>
</form>

{% endblock body %}